// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"
	"wameter/internal/server/data/ent/agent"
	"wameter/internal/server/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks    []Hook
	mutation *AgentMutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (au *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetHostname sets the "hostname" field.
func (au *AgentUpdate) SetHostname(s string) *AgentUpdate {
	au.mutation.SetHostname(s)
	return au
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (au *AgentUpdate) SetNillableHostname(s *string) *AgentUpdate {
	if s != nil {
		au.SetHostname(*s)
	}
	return au
}

// SetVersion sets the "version" field.
func (au *AgentUpdate) SetVersion(s string) *AgentUpdate {
	au.mutation.SetVersion(s)
	return au
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (au *AgentUpdate) SetNillableVersion(s *string) *AgentUpdate {
	if s != nil {
		au.SetVersion(*s)
	}
	return au
}

// SetStatus sets the "status" field.
func (au *AgentUpdate) SetStatus(s string) *AgentUpdate {
	au.mutation.SetStatus(s)
	return au
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (au *AgentUpdate) SetNillableStatus(s *string) *AgentUpdate {
	if s != nil {
		au.SetStatus(*s)
	}
	return au
}

// SetLastSeen sets the "last_seen" field.
func (au *AgentUpdate) SetLastSeen(t time.Time) *AgentUpdate {
	au.mutation.SetLastSeen(t)
	return au
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (au *AgentUpdate) SetNillableLastSeen(t *time.Time) *AgentUpdate {
	if t != nil {
		au.SetLastSeen(*t)
	}
	return au
}

// SetRegisteredAt sets the "registered_at" field.
func (au *AgentUpdate) SetRegisteredAt(t time.Time) *AgentUpdate {
	au.mutation.SetRegisteredAt(t)
	return au
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (au *AgentUpdate) SetNillableRegisteredAt(t *time.Time) *AgentUpdate {
	if t != nil {
		au.SetRegisteredAt(*t)
	}
	return au
}

// SetUpdatedAt sets the "updated_at" field.
func (au *AgentUpdate) SetUpdatedAt(t time.Time) *AgentUpdate {
	au.mutation.SetUpdatedAt(t)
	return au
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (au *AgentUpdate) SetNillableUpdatedAt(t *time.Time) *AgentUpdate {
	if t != nil {
		au.SetUpdatedAt(*t)
	}
	return au
}

// Mutation returns the AgentMutation object of the builder.
func (au *AgentUpdate) Mutation() *AgentMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AgentUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AgentUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AgentUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AgentUpdate) check() error {
	if v, ok := au.mutation.Hostname(); ok {
		if err := agent.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`ent: validator failed for field "Agent.hostname": %w`, err)}
		}
	}
	if v, ok := au.mutation.Version(); ok {
		if err := agent.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Agent.version": %w`, err)}
		}
	}
	if v, ok := au.mutation.Status(); ok {
		if err := agent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Agent.status": %w`, err)}
		}
	}
	return nil
}

func (au *AgentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Hostname(); ok {
		_spec.SetField(agent.FieldHostname, field.TypeString, value)
	}
	if value, ok := au.mutation.Version(); ok {
		_spec.SetField(agent.FieldVersion, field.TypeString, value)
	}
	if value, ok := au.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeString, value)
	}
	if value, ok := au.mutation.LastSeen(); ok {
		_spec.SetField(agent.FieldLastSeen, field.TypeTime, value)
	}
	if value, ok := au.mutation.RegisteredAt(); ok {
		_spec.SetField(agent.FieldRegisteredAt, field.TypeTime, value)
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentMutation
}

// SetHostname sets the "hostname" field.
func (auo *AgentUpdateOne) SetHostname(s string) *AgentUpdateOne {
	auo.mutation.SetHostname(s)
	return auo
}

// SetNillableHostname sets the "hostname" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableHostname(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetHostname(*s)
	}
	return auo
}

// SetVersion sets the "version" field.
func (auo *AgentUpdateOne) SetVersion(s string) *AgentUpdateOne {
	auo.mutation.SetVersion(s)
	return auo
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableVersion(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetVersion(*s)
	}
	return auo
}

// SetStatus sets the "status" field.
func (auo *AgentUpdateOne) SetStatus(s string) *AgentUpdateOne {
	auo.mutation.SetStatus(s)
	return auo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableStatus(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetStatus(*s)
	}
	return auo
}

// SetLastSeen sets the "last_seen" field.
func (auo *AgentUpdateOne) SetLastSeen(t time.Time) *AgentUpdateOne {
	auo.mutation.SetLastSeen(t)
	return auo
}

// SetNillableLastSeen sets the "last_seen" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableLastSeen(t *time.Time) *AgentUpdateOne {
	if t != nil {
		auo.SetLastSeen(*t)
	}
	return auo
}

// SetRegisteredAt sets the "registered_at" field.
func (auo *AgentUpdateOne) SetRegisteredAt(t time.Time) *AgentUpdateOne {
	auo.mutation.SetRegisteredAt(t)
	return auo
}

// SetNillableRegisteredAt sets the "registered_at" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableRegisteredAt(t *time.Time) *AgentUpdateOne {
	if t != nil {
		auo.SetRegisteredAt(*t)
	}
	return auo
}

// SetUpdatedAt sets the "updated_at" field.
func (auo *AgentUpdateOne) SetUpdatedAt(t time.Time) *AgentUpdateOne {
	auo.mutation.SetUpdatedAt(t)
	return auo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableUpdatedAt(t *time.Time) *AgentUpdateOne {
	if t != nil {
		auo.SetUpdatedAt(*t)
	}
	return auo
}

// Mutation returns the AgentMutation object of the builder.
func (auo *AgentUpdateOne) Mutation() *AgentMutation {
	return auo.mutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (auo *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Agent entity.
func (auo *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AgentUpdateOne) check() error {
	if v, ok := auo.mutation.Hostname(); ok {
		if err := agent.HostnameValidator(v); err != nil {
			return &ValidationError{Name: "hostname", err: fmt.Errorf(`ent: validator failed for field "Agent.hostname": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Version(); ok {
		if err := agent.VersionValidator(v); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`ent: validator failed for field "Agent.version": %w`, err)}
		}
	}
	if v, ok := auo.mutation.Status(); ok {
		if err := agent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Agent.status": %w`, err)}
		}
	}
	return nil
}

func (auo *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeString))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Hostname(); ok {
		_spec.SetField(agent.FieldHostname, field.TypeString, value)
	}
	if value, ok := auo.mutation.Version(); ok {
		_spec.SetField(agent.FieldVersion, field.TypeString, value)
	}
	if value, ok := auo.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeString, value)
	}
	if value, ok := auo.mutation.LastSeen(); ok {
		_spec.SetField(agent.FieldLastSeen, field.TypeTime, value)
	}
	if value, ok := auo.mutation.RegisteredAt(); ok {
		_spec.SetField(agent.FieldRegisteredAt, field.TypeTime, value)
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Agent{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
