// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"wameter/internal/server/data/ent/ipchange"
	"wameter/internal/server/data/ent/predicate"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// IPChangeQuery is the builder for querying IPChange entities.
type IPChangeQuery struct {
	config
	ctx        *QueryContext
	order      []ipchange.OrderOption
	inters     []Interceptor
	predicates []predicate.IPChange
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IPChangeQuery builder.
func (icq *IPChangeQuery) Where(ps ...predicate.IPChange) *IPChangeQuery {
	icq.predicates = append(icq.predicates, ps...)
	return icq
}

// Limit the number of records to be returned by this query.
func (icq *IPChangeQuery) Limit(limit int) *IPChangeQuery {
	icq.ctx.Limit = &limit
	return icq
}

// Offset to start from.
func (icq *IPChangeQuery) Offset(offset int) *IPChangeQuery {
	icq.ctx.Offset = &offset
	return icq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (icq *IPChangeQuery) Unique(unique bool) *IPChangeQuery {
	icq.ctx.Unique = &unique
	return icq
}

// Order specifies how the records should be ordered.
func (icq *IPChangeQuery) Order(o ...ipchange.OrderOption) *IPChangeQuery {
	icq.order = append(icq.order, o...)
	return icq
}

// First returns the first IPChange entity from the query.
// Returns a *NotFoundError when no IPChange was found.
func (icq *IPChangeQuery) First(ctx context.Context) (*IPChange, error) {
	nodes, err := icq.Limit(1).All(setContextOp(ctx, icq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{ipchange.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (icq *IPChangeQuery) FirstX(ctx context.Context) *IPChange {
	node, err := icq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IPChange ID from the query.
// Returns a *NotFoundError when no IPChange ID was found.
func (icq *IPChangeQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = icq.Limit(1).IDs(setContextOp(ctx, icq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{ipchange.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (icq *IPChangeQuery) FirstIDX(ctx context.Context) int64 {
	id, err := icq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IPChange entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IPChange entity is found.
// Returns a *NotFoundError when no IPChange entities are found.
func (icq *IPChangeQuery) Only(ctx context.Context) (*IPChange, error) {
	nodes, err := icq.Limit(2).All(setContextOp(ctx, icq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{ipchange.Label}
	default:
		return nil, &NotSingularError{ipchange.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (icq *IPChangeQuery) OnlyX(ctx context.Context) *IPChange {
	node, err := icq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IPChange ID in the query.
// Returns a *NotSingularError when more than one IPChange ID is found.
// Returns a *NotFoundError when no entities are found.
func (icq *IPChangeQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = icq.Limit(2).IDs(setContextOp(ctx, icq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{ipchange.Label}
	default:
		err = &NotSingularError{ipchange.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (icq *IPChangeQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := icq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IPChanges.
func (icq *IPChangeQuery) All(ctx context.Context) ([]*IPChange, error) {
	ctx = setContextOp(ctx, icq.ctx, ent.OpQueryAll)
	if err := icq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IPChange, *IPChangeQuery]()
	return withInterceptors[[]*IPChange](ctx, icq, qr, icq.inters)
}

// AllX is like All, but panics if an error occurs.
func (icq *IPChangeQuery) AllX(ctx context.Context) []*IPChange {
	nodes, err := icq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IPChange IDs.
func (icq *IPChangeQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if icq.ctx.Unique == nil && icq.path != nil {
		icq.Unique(true)
	}
	ctx = setContextOp(ctx, icq.ctx, ent.OpQueryIDs)
	if err = icq.Select(ipchange.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (icq *IPChangeQuery) IDsX(ctx context.Context) []int64 {
	ids, err := icq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (icq *IPChangeQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, icq.ctx, ent.OpQueryCount)
	if err := icq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, icq, querierCount[*IPChangeQuery](), icq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (icq *IPChangeQuery) CountX(ctx context.Context) int {
	count, err := icq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (icq *IPChangeQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, icq.ctx, ent.OpQueryExist)
	switch _, err := icq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (icq *IPChangeQuery) ExistX(ctx context.Context) bool {
	exist, err := icq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IPChangeQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (icq *IPChangeQuery) Clone() *IPChangeQuery {
	if icq == nil {
		return nil
	}
	return &IPChangeQuery{
		config:     icq.config,
		ctx:        icq.ctx.Clone(),
		order:      append([]ipchange.OrderOption{}, icq.order...),
		inters:     append([]Interceptor{}, icq.inters...),
		predicates: append([]predicate.IPChange{}, icq.predicates...),
		// clone intermediate query.
		sql:  icq.sql.Clone(),
		path: icq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		AgentID string `json:"agent_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IPChange.Query().
//		GroupBy(ipchange.FieldAgentID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (icq *IPChangeQuery) GroupBy(field string, fields ...string) *IPChangeGroupBy {
	icq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IPChangeGroupBy{build: icq}
	grbuild.flds = &icq.ctx.Fields
	grbuild.label = ipchange.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		AgentID string `json:"agent_id,omitempty"`
//	}
//
//	client.IPChange.Query().
//		Select(ipchange.FieldAgentID).
//		Scan(ctx, &v)
func (icq *IPChangeQuery) Select(fields ...string) *IPChangeSelect {
	icq.ctx.Fields = append(icq.ctx.Fields, fields...)
	sbuild := &IPChangeSelect{IPChangeQuery: icq}
	sbuild.label = ipchange.Label
	sbuild.flds, sbuild.scan = &icq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IPChangeSelect configured with the given aggregations.
func (icq *IPChangeQuery) Aggregate(fns ...AggregateFunc) *IPChangeSelect {
	return icq.Select().Aggregate(fns...)
}

func (icq *IPChangeQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range icq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, icq); err != nil {
				return err
			}
		}
	}
	for _, f := range icq.ctx.Fields {
		if !ipchange.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if icq.path != nil {
		prev, err := icq.path(ctx)
		if err != nil {
			return err
		}
		icq.sql = prev
	}
	return nil
}

func (icq *IPChangeQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IPChange, error) {
	var (
		nodes = []*IPChange{}
		_spec = icq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IPChange).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IPChange{config: icq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, icq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (icq *IPChangeQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := icq.querySpec()
	_spec.Node.Columns = icq.ctx.Fields
	if len(icq.ctx.Fields) > 0 {
		_spec.Unique = icq.ctx.Unique != nil && *icq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, icq.driver, _spec)
}

func (icq *IPChangeQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(ipchange.Table, ipchange.Columns, sqlgraph.NewFieldSpec(ipchange.FieldID, field.TypeInt64))
	_spec.From = icq.sql
	if unique := icq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if icq.path != nil {
		_spec.Unique = true
	}
	if fields := icq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ipchange.FieldID)
		for i := range fields {
			if fields[i] != ipchange.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := icq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := icq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := icq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := icq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (icq *IPChangeQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(icq.driver.Dialect())
	t1 := builder.Table(ipchange.Table)
	columns := icq.ctx.Fields
	if len(columns) == 0 {
		columns = ipchange.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if icq.sql != nil {
		selector = icq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if icq.ctx.Unique != nil && *icq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range icq.predicates {
		p(selector)
	}
	for _, p := range icq.order {
		p(selector)
	}
	if offset := icq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := icq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IPChangeGroupBy is the group-by builder for IPChange entities.
type IPChangeGroupBy struct {
	selector
	build *IPChangeQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (icgb *IPChangeGroupBy) Aggregate(fns ...AggregateFunc) *IPChangeGroupBy {
	icgb.fns = append(icgb.fns, fns...)
	return icgb
}

// Scan applies the selector query and scans the result into the given value.
func (icgb *IPChangeGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, icgb.build.ctx, ent.OpQueryGroupBy)
	if err := icgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IPChangeQuery, *IPChangeGroupBy](ctx, icgb.build, icgb, icgb.build.inters, v)
}

func (icgb *IPChangeGroupBy) sqlScan(ctx context.Context, root *IPChangeQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(icgb.fns))
	for _, fn := range icgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*icgb.flds)+len(icgb.fns))
		for _, f := range *icgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*icgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := icgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IPChangeSelect is the builder for selecting fields of IPChange entities.
type IPChangeSelect struct {
	*IPChangeQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ics *IPChangeSelect) Aggregate(fns ...AggregateFunc) *IPChangeSelect {
	ics.fns = append(ics.fns, fns...)
	return ics
}

// Scan applies the selector query and scans the result into the given value.
func (ics *IPChangeSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ics.ctx, ent.OpQuerySelect)
	if err := ics.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IPChangeQuery, *IPChangeSelect](ctx, ics.IPChangeQuery, ics, ics.inters, v)
}

func (ics *IPChangeSelect) sqlScan(ctx context.Context, root *IPChangeQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ics.fns))
	for _, fn := range ics.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ics.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ics.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
