services:
  server:
    image: ghcr.io/haiyon/wameter:latest
    container_name: wameter-server
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./log:/app/log
      - ./config:/app/config
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8080/api/v1/health" ]
      interval: 30s
      timeout: 5s
      retries: 3

  agent:
    image: ghcr.io/haiyon/wameter-agent:latest
    container_name: wameter-agent
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./log:/app/log
      - ./config:/app/config
    depends_on:
      - server
    healthcheck:
      test: [ "CMD", "wget", "-q", "--spider", "http://localhost:8081/api/v1/healthz" ]
      interval: 30s
      timeout: 5s
      retries: 3
