// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Agent is the predicate function for agent builders.
type Agent func(*sql.Selector)

// IPChange is the predicate function for ipchange builders.
type IPChange func(*sql.Selector)

// Metric is the predicate function for metric builders.
type Metric func(*sql.Selector)
