name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: ''

permissions:
  contents: write
  issues: write
  packages: write

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ github.event.inputs.version }}"
            if [[ ! "$VERSION" =~ ^v ]]; then
              VERSION="v$VERSION"
            fi
          else
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
          cache: true

      - name: Generate code
        run: make generate

      - name: Verify dependencies
        run: make verify

      - name: Run tests
        run: make test

      - name: Run linters
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
          args: --out-format=colored-line-number

  build-all:
    name: Build All Platforms
    needs: verify
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
          - os: linux
            arch: arm64
          - os: darwin
            arch: amd64
          - os: darwin
            arch: arm64
          - os: windows
            arch: amd64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
          cache: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Generate code
        run: make generate

      - name: Build for platform
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          VERSION: ${{ needs.verify.outputs.version }}
        run: |
          make build dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wameter-${{ needs.verify.outputs.version }}-${{ matrix.os }}-${{ matrix.arch }}
          path: dist/
          retention-days: 7

  docker-release:
    name: Docker Release
    needs: [ verify, build-all ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - name: server
            file: docker/server/Dockerfile
            suffix: ""
            platforms: linux/amd64,linux/arm64
          - name: agent
            file: docker/agent/Dockerfile
            suffix: -agent
            platforms: linux/amd64,linux/arm64

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate code
        run: make generate

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}${{ matrix.image.suffix }}
          tags: |
            type=semver,pattern={{version}},value=${{ needs.verify.outputs.version }}
            type=semver,pattern={{major}}.{{minor}},value=${{ needs.verify.outputs.version }}
            type=raw,value=latest,enable=${{ endsWith(needs.verify.outputs.version, '.0') }}
          labels: |
            org.opencontainers.image.title=Wameter ${{ matrix.image.name }}
            org.opencontainers.image.description=Wameter ${{ matrix.image.name }} - Monitoring ${{ matrix.image.name }}
            org.opencontainers.image.version=${{ needs.verify.outputs.version }}
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.licenses=MIT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.image.file }}
          platforms: ${{ matrix.image.platforms }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=build-${{ matrix.image.name }}
          cache-to: type=gha,scope=build-${{ matrix.image.name }},mode=max

  release:
    name: Create Release
    needs: [ verify, build-all, docker-release ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Generate checksums
        working-directory: artifacts
        run: |
          find . -type f -name "*.tar.gz" -exec sha256sum {} \; > sha256sums.txt

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ needs.verify.outputs.version }}
          files: |
            artifacts/**/*.tar.gz
            artifacts/sha256sums.txt
          draft: true
          prerelease: ${{ contains(needs.verify.outputs.version, '-rc') || contains(needs.verify.outputs.version, '-beta') || contains(needs.verify.outputs.version, '-alpha') }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
